name: proximity_transport
description: WiFi HTTPS (shelf) server/client, mDNS, TLS pinning, rate limits.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  proximity_protocol:
    path: ../protocol
  shelf: ^1.4.2
  basic_utils: ^5.8.2
  ed25519_edwards: ^0.3.2
  proximity_storage:
    path: ../storage

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
