// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD9p7bO5rGzEyH6n2RRZBrMy0G67rMcrk',
    appId: '1:355638335271:android:23a2e7c8dd958e36d0fb02',
    messagingSenderId: '355638335271',
    projectId: 'proximity-attendence',
    storageBucket: 'proximity-attendence.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC42l8zJxFs1kAq718PXHN0aTY5jLgwUqs',
    appId: '1:355638335271:ios:5e50a33356af0fc9d0fb02',
    messagingSenderId: '355638335271',
    projectId: 'proximity-attendence',
    storageBucket: 'proximity-attendence.firebasestorage.app',
    androidClientId: '355638335271-im3db3lnocimghunht2rp8ps01gigrv6.apps.googleusercontent.com',
    iosClientId: '355638335271-2qeu0tlr8qctga1rdbnej4s62alk3mqd.apps.googleusercontent.com',
    iosBundleId: 'org.iitbhilai.proximity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC42l8zJxFs1kAq718PXHN0aTY5jLgwUqs',
    appId: '1:355638335271:ios:5e50a33356af0fc9d0fb02',
    messagingSenderId: '355638335271',
    projectId: 'proximity-attendence',
    storageBucket: 'proximity-attendence.firebasestorage.app',
    androidClientId: '355638335271-im3db3lnocimghunht2rp8ps01gigrv6.apps.googleusercontent.com',
    iosClientId: '355638335271-2qeu0tlr8qctga1rdbnej4s62alk3mqd.apps.googleusercontent.com',
    iosBundleId: 'org.iitbhilai.proximity',
  );
}
